### ISSUE TITLE
Running with podman

### ISSUE THREAD

**Issue by your-local-developer** [sdv43/whaler#11]
I am trying to use this with podman, but I am getting this error:

Incorrect socket path "/run/podman/podman.sock"
I installed this app via flatpak and checked the configurations. /run/podman/podman.sock is allowed.

I am running podman version 3.4.4

**Comment by sdv43** [comment]
Hi, try to use this path "/run/user/1000/podman/podman.sock"

**Comment by your-local-developer** [comment]
That worked for me! Thank you so much 😺
