### ISSUE TITLE
Dark theme is horrible!

### ISSUE THREAD

**Issue by mbnoimi** [sdv43/whaler#13]
As you can see in the screenshot the dark theme is horrible. I'm unable to use the UI at all!
![image](https://user-images.githubusercontent.com/284547/209642857-e4ae1d0b-6592-4330-afc0-d0c55270a049.png)
- Linux Mint 21.1 Xfce
- Some logs:
```
Whaler - Docker Container Management

          ID: com.github.sdv43.whaler
         Ref: app/com.github.sdv43.whaler/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.2.0
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 5.4 MB
     Runtime: org.gnome.Platform/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: 86b90469df1190c77375670f778696777f48edefd236e931168fa6aea846ec29
      Parent: 5af628c3abbd2f6c5486b71e87ae7e196d3f41d62d91ff36810036bdae1921be
     Subject: Release 1.2.0 (b7470ea8)
        Date: 2022-07-07 21:58:43 +0000
```
```
$ flatpak info --show-permissions com.github.sdv43.whaler
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
filesystems=/home/laptop/.themes;xdg-run/podman/podman.sock;/run/docker.sock;/run/podman/podman.sock;/usr/share/themes;xdg-run/docker.sock;

[Environment]
GTK_THEME=Mint-Y-Dark-Aqua
QT_STYLE_OVERRIDE=Adwaita-dark
```

**Comment by topiga** [comment]
Maybe it's an issue with your machine ?
Mine works perfectly

**Comment by JGMelon22** [comment]
Facing the same issue. I've used Flatseal to include the following variable, however no success what so ever `GTK_THEME=Adwaita:dark`
![Screenshot_2024-07-13-20-19-53_2560x1080](https://github.com/user-attachments/assets/653022e1-2870-45b9-b759-24abdd796cd0)

**Comment by sdv43** [comment]
Hi! The app uses Elementary's set of colors, that's why you have these visual issues. 

If you want a dark theme, you should use Elementary's dark theme.
