### ISSUE TITLE
Keeps crashing on Fedora 37

### ISSUE THREAD

**Issue by lukatendai** [sdv43/whaler#14]
It connects to docker, I can see all containers and 5s later it crashes.

**Comment by lukatendai** [comment]
Thread 14 "pool-com.github" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdcbfe6c0 (LWP 30967)]
0x00007ffff72169c8 in Curl_httpchunk_read () from /lib64/libcurl.so.4
[Thread 0x7fffc27fc6c0 (LWP 30972) exited]
[Thread 0x7fffbb7fe6c0 (LWP 30969) exited]
[Thread 0x7fffdd3ff6c0 (LWP 30966) exited]
[Thread 0x7fffdf7fe6c0 (LWP 30950) exited]
[Thread 0x7fffdffff6c0 (LWP 30949) exited]
[Thread 0x7fffe4ffe6c0 (LWP 30948) exited]
[Thread 0x7fffe57ff6c0 (LWP 30947) exited]
[Thread 0x7ffff573aec0 (LWP 30943) exited]
[Thread 0x7fffdcbfe6c0 (LWP 30967) exited]

**Comment by lukatendai** [comment]
looks like something wrong with getting docker logs in src/Docker/ContainerLogWatcher.vala on line 180

**Comment by sdv43** [comment]
Hi! Does It happen when you try to click on a container card?
