### ISSUE TITLE
Cannot get list of docker containers 

### ISSUE THREAD

**Issue by Vortex-TH** [sdv43/whaler#2]
I'm getting the following error:
> Cannot get list of docker containers
> Cannot parse json from:

![whaler_error](https://user-images.githubusercontent.com/3118243/164891401-68fc1a3d-3916-4c03-88f0-6aa1fc0f9333.png)

I assume this is due to missing permissions since docker runs as root?

A more meaningful error message would be helpful.

**Comment by sdv43** [comment]
Hi, yes. I'm working on it.
