### ISSUE TITLE
No Licence ?

### ISSUE THREAD

**Issue by topiga** [sdv43/whaler#20]
Hey, it seems that you have no licence for your project, so your code is not open-source, but source-available. Is this a choice or a simple oversight on your end ?

**Comment by sdv43** [comment]
Hi, yes. It's simple oversight on my end). I'll fix it.

**Comment by topiga** [comment]
Okay !

**Comment by ieris19** [comment]
Any update on licensing @sdv43? I would like to open a pull request but don't feel comfortable if there's no clear license for the project

**Comment by sdv43** [comment]
@ieris19 Hi! Okay, that would be good.
