### ISSUE TITLE
Docker crashes if Whaler is left open?

### ISSUE THREAD

**Issue by Trainmaster2** [sdv43/whaler#22]
I've left Whaler open (on the overview screen) two nights in a row to monitor some containers. Both nights, I woke up to Whaler saying that the Docker API was unavailable, but both the docker command and restarting Whaler worked. However, my containers had stopped, suggesting to me that Docker crashed/restarted. Last night I closed Whaler, and my containers are still running.

I realize this is conjecture at this point. If you can point me to the Docker service or Whaler logs, I'd be happy to upload them along with this Issue.

**Comment by sdv43** [comment]
Hi! The application writes some logs, but not detailed ones, so that debugging can be done on them. 

Perhaps due to some optimization of the operating system (sleep mode or something similar), the connection is broken and such a bug appears. I think it will be hard to fix it, but I'll try somehow

**Comment by Trainmaster2** [comment]
I'd be happy to try it again tonight and upload the logs tomorrow.

**Comment by Trainmaster2** [comment]
Okay, I totally forgot to do this until the other day. However, I left Whaler open for a few days, and unfortunately (or maybe fortunately), nothing crashed. So, I have no logs for you, but maybe it was just a one-time issue?

**Comment by sdv43** [comment]
Yes, I think so. It's hard to reproduce such type of bugs.
