### ISSUE TITLE
Allow user to specify location of Docker socket

### ISSUE THREAD

**Issue by barthalion** [sdv43/whaler#4]
> @sdv43 This is not a blocker, but consider making the location of Docker socket configurable. For example, I run dockerd unprivileged, so the file is at `/run/user/1000/docker.sock` on my system, but Fedora/podman users are likely to have it at either `/run/user/1000/podman/podman.sock` or `/run/podman/podman.sock`. The `/run/user/1000` part can be grabbed through the `$XDG_RUNTIME_DIR` environment variable and should be accessible if you add something along `--filesystem=xdg-run/podman` (etc).

https://github.com/flathub/flathub/pull/3094#issuecomment-1118290663

**Comment by laxtiz** [comment]
well, i can used with podman on fedora linux. thanks
